In [ ]:
# dataframe
import pandas as pd
lst = ['Greek','For','Greek','is','portal','for','Greek']
df = pd.DataFrame(lst)
print(df)

        0
0   Greek
1     For
2   Greek
3      is
4  portal
5     for
6   Greek


In [ ]:
# ....
import pandas as pd
data={'Name':['Tom','nick','krish','jack'],'Age':[20,21,19,18]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
# 1. Write a Python program to calculate the following for a given list of numbers:
import statistics
import math

# Given list
numbers = [10, 20, 30, 40, 50, 20]

# Mean
mean_value = statistics.mean(numbers)

# Median
median_value = statistics.median(numbers)

# Mode
mode_value = statistics.mode(numbers)

# Variance
variance_value = statistics.variance(numbers)

# Standard Deviation
std_deviation = statistics.stdev(numbers)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation)

Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


In [ ]:

# 2. Create a NumPy array and perform the following operations:
import numpy as np

# Create NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Maximum and Minimum
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape the array (2x3)
reshaped_arr = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped_arr)

# Element-wise multiplication
multiplied = arr * 2
print("Element-wise Multiplication:\n", multiplied)

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Multiplication:
 [ 2  4  6  8 10 12]


In [ ]:
# 3. Write a Python program to:
import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix Multiplication
print("Matrix Multiplication:\n", np.dot(A, B))

# Transpose of matrix A
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [ ]:
# 4. Generate a random array of 10 numbers and calculate:
import numpy as np

# Generate random array of 10 numbers
random_array = np.random.rand(10)

print("Random Array:", random_array)

# Mean
print("Mean:", np.mean(random_array))

# Standard Deviation
print("Standard Deviation:", np.std(random_array))

# Minimum and Maximum
print("Minimum:", np.min(random_array))
print("Maximum:", np.max(random_array))

Random Array: [0.40497232 0.12190439 0.88437505 0.03524515 0.07286082 0.29967142
 0.73638145 0.51511992 0.45878372 0.90286319]
Mean: 0.4432177424771342
Standard Deviation: 0.3043299694090988
Minimum: 0.03524515107107673
Maximum: 0.9028631902840426


In [ ]:

# 5. Write a Python program using SciPy to:
import numpy as np
from scipy import stats

# Sample data
data = [10, 12, 9, 11, 10, 13, 12]

# Mean using scipy.stats
mean_value = stats.tmean(data)
print("Mean using scipy.stats:", mean_value)

# Perform one-sample t-test (compare against population mean = 10)
t_stat, p_value = stats.ttest_1samp(data, 10)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

Mean using scipy.stats: 11.0
T-Statistic: 1.8708286933869707
P-Value: 0.1105517404022668


In [ ]:
# 6. Write a Python program to compute definite integration of a mathematical function using scipy.integrate.
from scipy import integrate
import numpy as np

# Define function
def func(x):
    return x**2

# Integrate from 0 to 3
result, error = integrate.quad(func, 0, 3)

print("Definite Integration Result:", result)
print("Estimated Error:", error)

Definite Integration Result: 9.000000000000002
Estimated Error: 9.992007221626411e-14


In [ ]:
# 7. Write a Python program to minimize a mathematical function using scipy.optimize.
from scipy import optimize

# Define function
def func(x):
    return x**2 + 5*x + 6

# Minimize function
result = optimize.minimize(func, x0=0)

print("Minimum Value:", result.fun)
print("Value of x at Minimum:", result.x)

Minimum Value: -0.2499999999999991
Value of x at Minimum: [-2.50000002]


In [4]:
# Column Selection
import pandas as pd
data = {'Name':['Jai','Prince','Gaurav','Anuj'],'Age':[27,24,22,32],'Address':['delhi','kanpur','allahabad','kannauj'],'Qualification':['MSC','MA','MCA','Phd']}
df = pd.DataFrame(data)
print(df[['Name','Qualification']])

     Name Qualification
0     Jai           MSC
1  Prince            MA
2  Gaurav           MCA
3    Anuj           Phd


In [12]:
# Row Selection
import pandas as pd
data=pd.read_csv("/content/data.csv",index_col="name")
first=data.loc["Neha"]
second=data.loc["Arjun"]
print(first,"\n\n\n",second)

age              27
city        Kolkata
category          C
sales           300
a                 4
b                 6
Name: Neha, dtype: object 


 age             35
city        Jaipur
category         B
sales          200
a                1
b                9
Name: Arjun, dtype: object


In [13]:
# Program to implement Simple Linear Regression

def linear_regression(x, y):
    n = len(x)

    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum([x[i] * y[i] for i in range(n)])
    sum_x2 = sum([x[i] ** 2 for i in range(n)])

    # Calculating slope (b1) and intercept (b0)
    b1 = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x ** 2)
    b0 = (sum_y - b1 * sum_x) / n

    return b0, b1


# Example data
x = [1, 2, 3, 4, 5]
y = [2, 4, 5, 4, 5]

b0, b1 = linear_regression(x, y)

print("Intercept (b0):", b0)
print("Slope (b1):", b1)

# Predicting a value
x_new = 6
y_pred = b0 + b1 * x_new
print("Predicted value at x =", x_new, "is", y_pred)

Intercept (b0): 2.2
Slope (b1): 0.6
Predicted value at x = 6 is 5.8
